name: Analyze Bundle Size

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.3]
    
    env:
      CI: true

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm update

    - name: Analyze Bundle Size
      id: analyze_bundle_size
      run: |
        ANALYZE_RESULT=$(npm run analyze)
        npm run capture::server
        npm run capture::browser
        echo "::set-output name=analyze_result::$ANALYZE_RESULT"
        echo 'result\n'
        echo $ANALYZE_RESULT

    - name: debug
      id: debug
      env:
        CLI_LOG: ${{ steps.analyze_bundle_size.outputs.analyze_result }}
      run: |
        ESCAPED_CLI_LOG=$(echo $CLI_LOG | sed s/\'/\\\'/)
        echo $ESCAPED_CLI_LOG
        ESCAPED_CLI_LOG=$(echo $ESCAPED_CLI_LOG | sed s/\"/\\\"/)
        echo $ESCAPED_CLI_LOG
        echo "::set-output name=analyze_result::$ESCAPED_CLI_LOG"

    - name: Post to PR
      id: post_to_PR
      env:
        COMMENT_URL: ${{ github.event.pull_request.comments_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLI_LOG: ${{ steps.analyze_bundle_size.outputs.analyze_result }}
        SERVER_IMAGE_URL: ${{ steps.upload_server_result.outputs.browser_download_url }}
        BROWSER_IMAGE_URL: ${{ steps.upload_browser_result.outputs.browser_download_url }}
      run: |
        ESCAPED_CLI_LOG=$(echo $CLI_LOG | sed s/\'/\\\'/)
        echo $ESCAPED_CLI_LOG
        ESCAPED_CLI_LOG=$(echo $ESCAPED_CLI_LOG | sed s/\"/\\\"/)
        echo $ESCAPED_CLI_LOG
        curl \
          -X POST \
          $COMMENT_URL \
          -H "Content-Type: application/json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          --data '{ "body": "Analyzed Bundle Size\n![Server]('$SERVER_IMAGE_URL')\n![Browser]('$BROWSER_IMAGE_URL')\nCLI Result\n```'$ESCAPED_CLI_LOG'```" }'
