name: Analyze Bundle Size

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.3]
    
    env:
      CI: true

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm update

    - name: Analyze Bundle Size
      id: analyze_bundle_size
      run: |
        ANALYZE_RESULT=$(npm run analyze)
        npm run capture::server
        npm run capture::browser
        echo '::set-output name=analyze_result::"$ANALYZE_RESULT"'
        echo 'result\n'
        echo $ANALYZE_RESULT
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true
  
    - name: Upload Image of Analysis Results for server
      id: upload_server_result
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .analyze/server.png
        asset_name: server.png
        asset_content_type: image/png

    - name: Upload Image of Analysis Results for browser
      id: upload_browser_result
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .analyze/browser.png
        asset_name: browser.png
        asset_content_type: image/png

    - name: Post to PR
      id: post_to_PR
      env:
        COMMENT_URL: ${{ github.event.pull_request.comments_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLI_LOG: ${{ steps.analyze_bundle_size.outputs.analyze_result }}
        SERVER_IMAGE_URL: ${{ steps.upload_server_result.outputs.browser_download_url }}
        BROWSER_IMAGE_URL: ${{ steps.upload_browser_result.outputs.browser_download_url }}
      run: |
        curl \
          -X POST \
          $COMMENT_URL \
          -H "Content-Type: application/json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          --data '{ "body": "Analyzed Bundle Size\n![Server]('$SERVER_IMAGE_URL')\n![Browser]('$BROWSER_IMAGE_URL')\nCLI Result\n```'$CLI_LOG'```" }'
